### ISSUE TITLE
[Install Bug]: Satisfactory

### ISSUE THREAD

**Issue by itsadeadh2** [pelican-eggs/games-steamcmd#126]
### Panel Version

1.11.0

### Wings Version

1.11.13

### Service

satisfactory

### Modified

No, I did not modify the egg

### Expected Behavior

Install the server and have it running

### Actual Behavior

Server crashes on initialization, retries 2x and stops

### Steps To Reproduce

1. Imported the [egg-pterodactyl-satisfactory.json](https://github.com/pelican-eggs/games-steamcmd/blob/main/satisfactory/egg-pterodactyl-satisfactory.json) egg into Pterodactyl Panel
2. Configured a new server for the given egg
3. Got the error:
  ```shell
  :/home/container$ ./Engine/Binaries/Linux/FactoryServer-Linux-Shipping FactoryGame -Port=${SERVER_PORT}
  
  Refusing to run with the root privileges.
  
  libc++abi: __cxa_guard_acquire detected recursive initialization
  
  /entrypoint.sh: line 89:    42 Aborted                 (core dumped) ./Engine/Binaries/Linux/FactoryServer-Linux-Shipping FactoryGame -Port=${SERVER_PORT}
  ```

### Install logs

https://pastebin.com/7DfwEJxg

**Comment by gOOvER** [comment]
never saw such an Error and cant confirm.

pls more Infos about your System

**Comment by itsadeadh2** [comment]
@gOOvER 
I'm running the [docker version of wings](https://github.com/pterodactyl/wings/blob/develop/Dockerfile) and the provided command in the issue template to retrieve logs did not work for me, the container doesn't appear to have sh or bash available for me to run commands.

Here is some more general info about my system:
- Everything is running in docker containers orchestrated by docker-compose
- I was already able to get other servers up and running on the instance

If you want me to post some specific info about my system please tell me and I can try to retrieve it for you

**Comment by gOOvER** [comment]
sry, but this is No Egg issue. please ask in ptero discord for Support.

Satisfactory Egg Runs fine

**Comment by itsadeadh2** [comment]
I was able to fix it by appending `su - container -c ` in the startup command:
```sh
su - container -c "./Engine/Binaries/Linux/*-Linux-Shipping FactoryGame -Port={{SERVER_PORT}}"
```  

Not exactly sure why is that, but since the error message mentioned `Refusing to run with the root privileges` I decided to give it a shot by attempting to use the `container` user declared in the [steamcmd image](https://github.com/pelican-eggs/yolks/blob/e52ceeae2ac67223cb49b849cb20e3ceff9114c4/steamcmd/debian/Dockerfile#L29)

**Comment by QuintenQVD0** [comment]
> I was able to fix it by appending `su - container -c ` in the startup command:
> 
> su - container -c "./Engine/Binaries/Linux/*-Linux-Shipping FactoryGame -Port={{SERVER_PORT}}"
> Not exactly sure why is that, but since the error message mentioned `Refusing to run with the root privileges` I decided to give it a shot by attempting to use the `container` user declared in the [steamcmd image](https://github.com/pelican-eggs/yolks/blob/e52ceeae2ac67223cb49b849cb20e3ceff9114c4/steamcmd/debian/Dockerfile#L29)

You messed up your wings compose file as it is running as root.

**Comment by itsadeadh2** [comment]
@QuintenQVD0 Yeah, I was inspecting my docker-compose file and I found out that WINGS_USERNAME was set as root:
```yml
wings:
    image: ghcr.io/pterodactyl/wings:latest
    restart: always
    # These are the ports exposed by Wings, I don't recommend changing them.
    ports:
      - "2022:2022"
    tty: true
    environment:
      TZ: "America/New_York"
      # For ease of setup, this is going to use root user.
      WINGS_UID: 0
      WINGS_GID: 0
      WINGS_USERNAME: root # messed it up here
    ...
```
This is just a copy-paste of a docker-compose I found online, will attempt to fix it whenever I have the time lol
Anyways, thanks guys
